
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apl.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ar_ccliente
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ar_ccliente()
    {

        this.ArClientes = new HashSet<ar_cliente>();

        this.ArInvoices = new HashSet<ar_invoice>();

    }


    public int Id { get; set; }

    public string ArCClienteCod { get; set; }

    public string Nombre { get; set; }

    public int IdEdif { get; set; }

    public int UserCreated { get; set; }

    public System.DateTime DateCreated { get; set; }

    public Nullable<int> UserUpdated { get; set; }

    public Nullable<System.DateTime> DateUpdated { get; set; }

    public bool IsActive { get; set; }

    public int IdGlAcct { get; set; }



    public virtual ar_option ArOption { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ar_cliente> ArClientes { get; set; }

    public virtual gl_account GlAccount { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ar_invoice> ArInvoices { get; set; }

}

}
