
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apl.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ar_option
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ar_option()
    {

        this.ArCClientes = new HashSet<ar_ccliente>();

    }


    public int IdEdif { get; set; }

    public int NextInvcNo { get; set; }

    public byte InvcNoSize { get; set; }

    public int UserCreated { get; set; }

    public System.DateTime DateCreated { get; set; }

    public Nullable<int> UserUpdated { get; set; }

    public Nullable<System.DateTime> DateUpdated { get; set; }

    public Nullable<int> IdGlAcctAnticipo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ar_ccliente> ArCClientes { get; set; }

    public virtual gl_account GlAccount { get; set; }

}

}
