
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apl.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class gl_account
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public gl_account()
    {

        this.GlTransactions = new HashSet<gl_transaction>();

        this.ArOptions = new HashSet<ar_option>();

        this.ArCClientes = new HashSet<ar_ccliente>();

    }


    public int Id { get; set; }

    public string GlAcctNo { get; set; }

    public string Nombre { get; set; }

    public bool IsActive { get; set; }

    public int UserCreated { get; set; }

    public System.DateTime DateCreated { get; set; }

    public Nullable<int> UserUpdated { get; set; }

    public Nullable<System.DateTime> DateUpdated { get; set; }

    public int IdNaturalAcct { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<gl_transaction> GlTransactions { get; set; }

    public virtual gl_natural_acct GlNaturalAcct { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ar_option> ArOptions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ar_ccliente> ArCClientes { get; set; }

}

}
