
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apl.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class gl_option
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public gl_option()
    {

        this.GlVouchers = new HashSet<gl_voucher>();

        this.GlNaturalAccts = new HashSet<gl_natural_acct>();

    }


    public int IdEdif { get; set; }

    public string AcctMask { get; set; }

    public string AcctMaskDelimiter { get; set; }

    public byte AcctNoSize { get; set; }

    public int UserCreated { get; set; }

    public System.DateTime DateCreated { get; set; }

    public Nullable<int> UserUpdated { get; set; }

    public Nullable<System.DateTime> DateUpdated { get; set; }

    public short NextVoucherNo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<gl_voucher> GlVouchers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<gl_natural_acct> GlNaturalAccts { get; set; }

}

}
