//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apl.Business.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ar_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ar_cliente()
        {
            this.ArInvoices = new HashSet<ar_invoice>();
        }
    
        public int Id { get; set; }
        public int IdCCliente { get; set; }
        public int UserCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> UserUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public bool IsActive { get; set; }
        public bool Flag1 { get; set; }
        public int IdEntidad { get; set; }
    
        public virtual ar_ccliente ArCCliente { get; set; }
        public virtual entidad Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ar_invoice> ArInvoices { get; set; }
    }
}
