//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apl.Business.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ar_taxinvc
    {
        public int Id { get; set; }
        public int IdInvoice { get; set; }
        public decimal TaxAmt { get; set; }
        public bool IsPercentage { get; set; }
        public decimal Valor { get; set; }
        public string Nombre { get; set; }
        public bool IsIva { get; set; }
        public decimal Base { get; set; }
    
        public virtual ar_invoice ArInvoice { get; set; }
    }
}
