//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apl.Business.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class entidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public entidad()
        {
            this.ArClientes = new HashSet<ar_cliente>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string CodId { get; set; }
        public bool IsNatural { get; set; }
        public bool IsActive { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Movil { get; set; }
        public int IdPais { get; set; }
        public int IdAdminPropiedades { get; set; }
        public int UserCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> UserUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string Direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ar_cliente> ArClientes { get; set; }
    }
}
