//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apl.Business.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_acctcat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gl_acctcat()
        {
            this.GlNaturalAccts = new HashSet<gl_natural_acct>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int UserCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> UserUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gl_natural_acct> GlNaturalAccts { get; set; }
    }
}
