//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apl.Business.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_natural_acct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gl_natural_acct()
        {
            this.GlAccounts = new HashSet<gl_account>();
        }
    
        public int Id { get; set; }
        public string NaturalAcctNo { get; set; }
        public string Nombre { get; set; }
        public int IdAcctCat { get; set; }
        public int IdEdif { get; set; }
        public int UserCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> UserUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public bool IsActive { get; set; }
    
        public virtual gl_option GlOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gl_account> GlAccounts { get; set; }
        public virtual gl_acctcat GlAcctCat { get; set; }
    }
}
