
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apl.Business.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class gl_transaction
{

    public int Id { get; set; }

    public int IdGlAcct { get; set; }

    public decimal TranAmt { get; set; }

    public string Cmnt { get; set; }

    public string TranId { get; set; }

    public byte SubTranType { get; set; }

    public int IdVoucher { get; set; }



    public virtual gl_account GlAccount { get; set; }

    public virtual gl_voucher GlVoucher { get; set; }

}

}
