
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Apl.Business.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class gl_voucher
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public gl_voucher()
    {

        this.GlTransactions = new HashSet<gl_transaction>();

    }


    public int Id { get; set; }

    public int UserCreated { get; set; }

    public System.DateTime DateCreated { get; set; }

    public Nullable<int> UserUpdated { get; set; }

    public Nullable<System.DateTime> DateUpdated { get; set; }

    public int IdEdif { get; set; }

    public System.DateTime TranDate { get; set; }

    public int IdMPeriod { get; set; }

    public int TranKey { get; set; }

    public bool IsCancel { get; set; }

    public Nullable<System.DateTime> DateCanceled { get; set; }

    public string VoucherId { get; set; }

    public string Cmnt { get; set; }

    public byte TranType { get; set; }

    public string Modulo { get; set; }

    public int VoucherNo { get; set; }



    public virtual gl_option GlOption { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<gl_transaction> GlTransactions { get; set; }

}

}
