//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apl.Business.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ie_subcat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ie_subcat()
        {
            this.ArInvDetails = new HashSet<ar_invdetail>();
        }
    
        public int Id { get; set; }
        public string IgEgSubCatCod { get; set; }
        public string Concepto { get; set; }
        public int IdIgEgCat { get; set; }
        public bool ReadOnly { get; set; }
        public int IdGlAcct { get; set; }
        public int UserCreated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> UserUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> IdClassTax { get; set; }
        public Nullable<int> IdClassDeduc { get; set; }
        public decimal Precio { get; set; }
        public bool IsExpense { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ar_invdetail> ArInvDetails { get; set; }
    }
}
